apiVersion: apps/v1
kind: Deployment
metadata:
    name: ubuntu-ma-latest1
    labels:
        app: ubuntu-ma-latest1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ubuntu-ma-latest1
    template:
        metadata:
            labels:
                app: ubuntu-ma-latest1
        spec:
            containers:
                - name: ubuntu-tools
                  image: ubuntu:latest
                  env:
                      - name: TZ
                        value: "America/New_York"
                      - name: DEBIAN_FRONTEND
                        value: "noninteractive"
                      - name: APT_PROXY
                        value: "http://apt-cacher-ng-service:3142"
                  imagePullPolicy: IfNotPresent
                  command: ["/bin/bash"]
                  args:
                      - "-c"
                      - |
                          echo "Updating packages..."
                          apt update
                          apt install -y git default-jdk make
                          apt install -y python3 python3-pip python3-venv 
                          echo "Keep container running..."
                          tail -f /dev/null
                  resources:
                      limits:
                          cpu: "4"
                      requests:
                          cpu: "1"
                  volumeMounts:
                      - name: pv-home
                        mountPath: /home
                      - name: pv-workspaces
                        mountPath: /workspaces
            volumes:
                - name: pv-home
                  persistentVolumeClaim:
                      claimName: pv-home
                - name: pv-workspaces
                  persistentVolumeClaim:
                      claimName: pv-workspaces
