apiVersion: apps/v1
kind: Deployment
metadata:
    name: vsc-ubuntu-ma
spec:
    replicas: 1
    selector:
        matchLabels:
            app: vsc-ubuntu-ma
    template:
        metadata:
            labels:
                app: vsc-ubuntu-ma
        spec:
            initContainers:
              - name: configure-proxy
                image: hittjw/vsc-ubuntu-ma:latest
                command:
                    [
                        "bash",
                        "-c",
                        'echo "Acquire::http::Proxy \"http://apt-cacher-ng-service:3142\";" > /etc/apt/apt.conf.d/00proxy',
                    ]
                volumeMounts:
                    - name: apt-conf-storage
                      mountPath: /etc/apt/apt.conf.d/
            containers:
              - name: vsc-ubuntu-ma
                image: hittjw/vsc-ubuntu-ma:latest
                env:
                      - name: TZ
                        value: "America/New_York"
                      - name: DEBIAN_FRONTEND
                        value: "noninteractive"
                      - name: APT_PROXY
                        value: "http://apt-cacher-ng-service:3142"
                imagePullPolicy: IfNotPresent
                resources:
                      limits:
                          cpu: "4"
                      requests:
                          cpu: "1"
                volumeMounts:
                  - name: apt-conf-storage
                    mountPath: /etc/apt/apt.conf.d/
                  - name: pv-home
                    mountPath: /home
                  - name: pv-workspaces
                    mountPath: /workspaces  
            volumes:
                - name: apt-conf-storage
                  emptyDir: {}
                - name: pv-home
                  persistentVolumeClaim:
                      claimName: pv-home
                - name: pv-workspaces
                  persistentVolumeClaim:
                      claimName: pv-workspaces